## Importing the library 

In [1]:
import numpy as np

### Create an one dimensional array

In [2]:
num = [1,2,3,4,5]
num = np.array(num)
num

array([1, 2, 3, 4, 5])

### Creating a Two-Dimensional array

In [3]:
num = [[1,2,3,4],[5,6,7,8]]
num = np.array(num)
num

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Checking the dimension of the array

In [4]:
num.ndim

2

### Checking the shape of teh array

In [5]:
num.shape

(2, 4)

### Getting the size of the array

In [6]:
num.size

8

### Getting the datatype of a variable

In [7]:
num.dtype

dtype('int64')

### Creating an array using the zeros function

In [8]:
num = np.zeros(5)
num

array([0., 0., 0., 0., 0.])

### creating a two dimensional array using the zeros function

In [9]:
num = np.zeros((5,5))
num

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Creating an array using the ones function

In [10]:
num = np.ones(4)
num

array([1., 1., 1., 1.])

### Creating an two dimensional array using the ones function

In [11]:
num = np.ones((5,5))
num

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Creating  a diagnoal matrix to ones and other element to zeros

In [12]:
num = np.eye(4)
num

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Creating a square matrix

In [13]:
num = np.diag([1,2,3,4,5])
num

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### Getting the diagonal of the array using the diag function

In [14]:
num = ([1,2,3,4],[5,6,4,8],[9,10,11,12],[13,14,15,16])
num = np.array(num)
num = np.diag(num)
num

array([ 1,  6, 11, 16])

### Generating the random number between the number which we specify by using the random function

In [15]:
num = np.random.randint(10,20,4)
num

array([17, 11, 13, 15])

### Generating the random number between 0 and 1 using rand function

In [16]:
num = np.random.rand(5)
num

array([0.05035348, 0.34896451, 0.7770278 , 0.58691296, 0.6356991 ])

### Generating a two dimensional array using the rand function

In [17]:
num = np.random.rand(5,2)
num

array([[0.84590927, 0.11268293],
       [0.39392254, 0.03724412],
       [0.64765339, 0.03582549],
       [0.74168541, 0.51629458],
       [0.70555246, 0.84476805]])

### Getting the random number which is centered to zero i.e zero will be the center by using randn function

In [18]:
num = np.random.randn(4)
num

array([ 0.55312562, -0.01735536,  1.47255563,  1.34950345])

### Getting the random two dimensional array which is centered to zero i.e zero will be the center by using randn function

In [19]:
num = np.random.randn(4,2)
num

array([[ 0.03609927, -0.79912061],
       [ 0.63739911,  0.53589024],
       [-0.50806882, -0.90989711],
       [-0.01944074,  1.20630133]])

### Reshaping the one dimensional data to any dimension by using the reshape function

In [20]:
num = np.random.randint(1,100,40)
num = num.reshape(8,5)
num

array([[ 1, 39, 96, 14, 20],
       [63, 65, 50, 99, 54],
       [23, 13, 47, 97, 90],
       [39, 66, 78, 70, 77],
       [53, 42, 91, 96, 65],
       [25, 25, 55, 96, 95],
       [14, 71, 64, 69, 93],
       [10, 29, 11, 21, 40]])

### Genarating the same random array after every exectuion by using the seed function

In [21]:
np.random.seed(12)
arr = np.random.randint(1,101,20)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50, 53,  6, 14, 90, 35, 76, 75,
        1, 77, 14])

### Genarating the same random two dimensional array after every exectuion by using the seed function

In [22]:
np.random.seed(12)
arr = np.random.randint(1,101,20)
arr = arr.reshape(4,5)
arr

array([[76, 28,  7,  3,  4],
       [68, 77, 49, 23, 50],
       [53,  6, 14, 90, 35],
       [76, 75,  1, 77, 14]])

### So when we do not use the seed function the data will get change after every execution

In [23]:
arr = np.random.randint(1,101,20)
arr = arr.reshape(4,5)
arr

array([[83, 90, 36, 63, 36],
       [34, 31, 64, 97, 19],
       [87, 51, 81, 85,  7],
       [74, 46, 31, 33, 28]])

### Getting the count of number present in a variable

In [24]:
arr.size

20

## Indexing

In [25]:
np.random.seed(12)
arr = np.random.randint(1,101,36)
arr = arr.reshape(6,6)
arr

array([[76, 28,  7,  3,  4, 68],
       [77, 49, 23, 50, 53,  6],
       [14, 90, 35, 76, 75,  1],
       [77, 14, 83, 90, 36, 63],
       [36, 34, 31, 64, 97, 19],
       [87, 51, 81, 85,  7, 74]])

#### Getting a whole row

In [26]:
arr[1]

array([77, 49, 23, 50, 53,  6])

#### Getting a whole column

In [27]:
arr[:1]

array([[76, 28,  7,  3,  4, 68]])

#### Getting a particular value i.e second row first column

In [28]:
arr[2,1]

90

In [29]:
arr[2,2]

35

In [30]:
arr[4,3]

64

## Slicing

In [31]:
np.random.seed(12)
arr = np.random.randint(1,101,36)
arr = arr.reshape(6,6)
arr

array([[76, 28,  7,  3,  4, 68],
       [77, 49, 23, 50, 53,  6],
       [14, 90, 35, 76, 75,  1],
       [77, 14, 83, 90, 36, 63],
       [36, 34, 31, 64, 97, 19],
       [87, 51, 81, 85,  7, 74]])

In [32]:
arr[:2,:3]

array([[76, 28,  7],
       [77, 49, 23]])

In [33]:
arr[1:4,4:5]

array([[53],
       [75],
       [36]])

# Some important function of numpy

In [34]:
arr

array([[76, 28,  7,  3,  4, 68],
       [77, 49, 23, 50, 53,  6],
       [14, 90, 35, 76, 75,  1],
       [77, 14, 83, 90, 36, 63],
       [36, 34, 31, 64, 97, 19],
       [87, 51, 81, 85,  7, 74]])

### Getting the maximum number from an array

In [35]:
np.max(arr)

97

### Getting the maximum number from an array

In [36]:
np.min(arr)

1

### Getting the positon of minimum number from an array

In [37]:
np.argmin(arr)

17

### Getting the position of maximum number from an array

In [38]:
np.argmax(arr)

28

### Getting the square root of every number from the arrays

In [39]:
np.sqrt(arr)

array([[8.71779789, 5.29150262, 2.64575131, 1.73205081, 2.        ,
        8.24621125],
       [8.77496439, 7.        , 4.79583152, 7.07106781, 7.28010989,
        2.44948974],
       [3.74165739, 9.48683298, 5.91607978, 8.71779789, 8.66025404,
        1.        ],
       [8.77496439, 3.74165739, 9.11043358, 9.48683298, 6.        ,
        7.93725393],
       [6.        , 5.83095189, 5.56776436, 8.        , 9.8488578 ,
        4.35889894],
       [9.32737905, 7.14142843, 9.        , 9.21954446, 2.64575131,
        8.60232527]])

#### Getting the sin of every number from the array

In [40]:
np.sin(arr)

array([[ 0.56610764,  0.27090579,  0.6569866 ,  0.14112001, -0.7568025 ,
        -0.89792768],
       [ 0.99952016, -0.95375265, -0.8462204 , -0.26237485,  0.39592515,
        -0.2794155 ],
       [ 0.99060736,  0.89399666, -0.42818267,  0.56610764, -0.38778164,
         0.84147098],
       [ 0.99952016,  0.99060736,  0.96836446,  0.89399666, -0.99177885,
         0.1673557 ],
       [-0.99177885,  0.52908269, -0.40403765,  0.92002604,  0.37960774,
         0.14987721],
       [-0.82181784,  0.67022918, -0.62988799, -0.17607562,  0.6569866 ,
        -0.98514626]])

#### Getting the cos of every number from the array

In [41]:
np.cos(arr)

array([[ 0.82433133, -0.96260587,  0.75390225, -0.9899925 , -0.65364362,
         0.44014302],
       [-0.03097503,  0.30059254, -0.53283302,  0.96496603, -0.91828279,
         0.96017029],
       [ 0.13673722, -0.44807362, -0.90369221,  0.82433133,  0.92175127,
         0.54030231],
       [-0.03097503,  0.13673722,  0.24954012, -0.44807362, -0.12796369,
         0.98589658],
       [-0.12796369, -0.84857027,  0.91474236,  0.39185723, -0.92514754,
         0.98870462],
       [ 0.56975033,  0.7421542 ,  0.77668598, -0.98437664,  0.75390225,
         0.17171734]])

### Getting the number which are evenly spaced

In [42]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

### Creating any random value within any range using the Empty Function

In [47]:
num = np.empty((4,4))
num

array([[4.67968230e-310, 0.00000000e+000, 6.92275158e-310,
        6.92275158e-310],
       [6.92275158e-310, 6.92275158e-310, 6.92275158e-310,
        6.92275158e-310],
       [6.92275158e-310, 6.92275158e-310, 6.92275158e-310,
        6.92275158e-310],
       [6.92275158e-310, 6.92275158e-310, 6.92275186e-310,
        6.92275186e-310]])

### Creating the values on an particular range using the arange fuction

In [50]:
num = np.arange(1,21)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Creating the a range of number with the step of two

In [53]:
num = np.arange(1,21,2)
num

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Creating multidimensional array to one dimensional array by using the ravel function

In [58]:
np.ravel(arr)

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50, 53,  6, 14, 90, 35, 76, 75,
        1, 77, 14, 83, 90, 36, 63, 36, 34, 31, 64, 97, 19, 87, 51, 81, 85,
        7, 74])

### Creating multidimensional array to one dimensional array by using the ravel function

In [59]:
np.ravel(arr)

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50, 53,  6, 14, 90, 35, 76, 75,
        1, 77, 14, 83, 90, 36, 63, 36, 34, 31, 64, 97, 19, 87, 51, 81, 85,
        7, 74])

In [60]:
arr

array([[76, 28,  7,  3,  4, 68],
       [77, 49, 23, 50, 53,  6],
       [14, 90, 35, 76, 75,  1],
       [77, 14, 83, 90, 36, 63],
       [36, 34, 31, 64, 97, 19],
       [87, 51, 81, 85,  7, 74]])

In [63]:
arr = np.arange(1,22)
arr = arr.reshape(3,7)
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

### Creating the transpose of a matrix using the transpose function

In [65]:
arr.transpose()

array([[ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20],
       [ 7, 14, 21]])

### Adding two arrays

In [67]:
arr_1 = [1,2,3,4,5]
arr_2 = [6,7,8,9,10]

np.add(arr_1,arr_2)

array([ 7,  9, 11, 13, 15])

### Getting the average of the function using the mean function

In [72]:
np.mean(arr)

11.0

### Getting the standard division of an array using the std function

In [73]:
np.std(arr)

6.0553007081949835

### Getting the exponential of an array using the exp function

In [77]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
        1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08, 4.85165195e+08, 1.31881573e+09]])

### Getting the Log of an array using the log function

In [78]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527, 2.48490665,
        2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
        2.99573227, 3.04452244]])

In [79]:
np.log10(arr)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
        0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269, 1.07918125,
        1.11394335, 1.14612804],
       [1.17609126, 1.20411998, 1.23044892, 1.25527251, 1.2787536 ,
        1.30103   , 1.32221929]])

### Joining two arrays using the concantenation function

In [82]:
np.concatenate((arr_1,arr_2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Joining two arrays in the vertical dimension using the vstack function

In [85]:
np.vstack((arr_1,arr_2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Joining two arrays in the horizontal dimension using the hstack function

In [86]:
np.hstack((arr_1,arr_2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Splitting the array using the split function

In [90]:
np.split(arr,3)

[array([[1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21]])]